### ISSUE TITLE
Update permissions

### ISSUE THREAD

**Issue by davidmascharka** [davidmascharka/LIPS#2]
Need to use the new permissions scheme to work with newer devices instead of ugly try/catch and hope the user isn't on a newer device

**Comment by davidmascharka** [comment]
We request runtime permissions on devices >= Marshmallow now. Need to fix up the try/catch blocks

**Comment by maheshgaya** [comment]
I added the new permission implementation. Remove ".txt" from the file.
[MainActivity.java.txt](https://github.com/davidmascharka/LIPS/files/232725/MainActivity.java.txt)

Also delete "android-support-v4.jar" from "~/LIPS-master/app/libs/" folder: 
        == This fixes a compiling issue "Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat"

**Comment by davidmascharka** [comment]
If you could submit a pull request that would be great

**Comment by davidmascharka** [comment]
Fixed in 13e8838
